# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [ ]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [1]:
import numpy as np

# Creating the list
my_list = [1, 2, 3, 4, 5]

# Creating an array with the same values
my_arr = np.array(my_list)

# Displaying both
print("List:", my_list)
print("Array:", my_arr)


List: [1, 2, 3, 4, 5]
Array: [1 2 3 4 5]


2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [2]:
import numpy as np

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating an array with the same values
my_arr = np.array(my_list)

# Multiply the list by 4
list_result = my_list * 4

# Multiply the NumPy array by 4
arr_result = my_arr * 4

# Print the results
print("List multiplied by 4:", list_result)
print("array multiplied by 4:", arr_result)

# Explanation:
# When we multiply a list by 4, it repeats the list 4 times.
# When we multiply an array by 4, it multiplies each element of the array by 4.


List multiplied by 4: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
array multiplied by 4: [ 4  8 12 16 20]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [4]:
import numpy as np

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a NumPy array with the same values
my_arr = np.array(my_list)

# Add the list with itself
list_sum = my_list + my_list

# Add the NumPy array with itself
arr_sum = my_arr + my_arr

# Add the list with the NumPy array
# This will cause a TypeError because Python lists and NumPy arrays are different types
try:
    list_arr_sum = my_list + my_arr
except TypeError as e:
    list_arr_sum = str(e)

# Print the results
print("List added with itself:", list_sum)
print("array added with itself:", arr_sum)
print("List added with array:", list_arr_sum)

# Explanation:
# - Adding a Python list with itself results in the list being concatenated with itself (repeated).
# - Adding a NumPy array with itself performs element-wise addition.
# - Adding a Python list with a NumPy array results in a TypeError because they are different types.


List added with itself: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
array added with itself: [ 2  4  6  8 10]
List added with NumPy array: [ 2  4  6  8 10]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [10]:
import numpy as np

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a NumPy array with the same values
my_arr = np.array(my_list)

# Subtract the list from itself (This will raise an error)
try:
    list_subtraction = my_list - my_list
except TypeError as e:
    list_subtraction = str(e)

# Subtract the NumPy array from itself
arr_subtraction = my_arr - my_arr

# Subtract the list from the NumPy array (This will raise an error)
try:
    list_arr_subtraction = my_list - my_arr
except TypeError as e:
    list_arr_subtraction = str(e)

# Print the results
print("List subtracted from itself:", list_subtraction)
print("NumPy array subtracted from itself:", arr_subtraction)
print("List subtracted from NumPy array:", list_arr_subtraction)

# Explanation:
# - Subtracting a Python list from itself will raise a TypeError, as Python lists do not support subtraction directly.
# - Subtracting a NumPy array from itself will result in an array of zeros, as each element is subtracted by itself.
# - Subtracting a Python list from a NumPy array raises a TypeError because they are different types and cannot be directly subtracted.


List subtracted from itself: unsupported operand type(s) for -: 'list' and 'list'
NumPy array subtracted from itself: [0 0 0 0 0]
List subtracted from NumPy array: [0 0 0 0 0]


5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [9]:
import numpy as np

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a NumPy array with the same values
my_arr = np.array(my_list)

# Multiply the list with itself
try:
    list_product = my_list * my_list
except TypeError as e:
    list_product = str(e)

# Multiply the NumPy array with itself
arr_product = my_arr * my_arr

# Multiply the list with the NumPy array (This will raise an error)
try:
    list_arr_product = my_list * my_arr
except TypeError as e:
    list_arr_product = str(e)

# Print the results
print("List multiplied with itself:", list_product)
print("NumPy array multiplied with itself:", arr_product)
print("List multiplied by NumPy array:", list_arr_product)

# Explanation:
# - When you multiply a Python list by another list, it will result in a TypeError because lists do not support element-wise multiplication.
# - When you multiply a NumPy array by itself, it performs element-wise multiplication, resulting in a new array where each element is squared.
# - Multiplying a Python list with a NumPy array raises a TypeError because they are different types, and multiplication isn't defined for them directly.


List multiplied with itself: can't multiply sequence by non-int of type 'list'
NumPy array multiplied with itself: [ 1  4  9 16 25]
List multiplied by NumPy array: [ 1  4  9 16 25]


7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [8]:
import numpy as np

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Creating a array with the same values
my_arr = np.array(my_list)

# Divide the list by itself (This will raise an error)
try:
    list_division = my_list / my_list
except TypeError as e:
    list_division = str(e)

# Divide the array by itself
arr_division = my_arr / my_arr

# Divide the list by the array (This will raise an error)
try:
    list_arr_division = my_list / my_arr
except TypeError as e:
    list_arr_division = str(e)

# Print the results
print("List divided by itself:", list_division)
print("array divided by itself:", arr_division)
print("List divided by array:", list_arr_division)

# Explanation:
# - Dividing a Python list by itself will raise a TypeError, as Python lists do not support division directly.
# - Dividing a NumPy array by itself will result in an array of ones (since any number divided by itself is 1).
# - Dividing a Python list by a NumPy array raises a TypeError because they are different types and cannot be directly divided.


List divided by itself: unsupported operand type(s) for /: 'list' and 'list'
array divided by itself: [1. 1. 1. 1. 1.]
List divided by array: [1. 1. 1. 1. 1.]


8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [33]:
# An array operates more like a matrix would than a list which operates like a set.
# For example you cannot subtract lists or multiply them or divide them but you can for arrays.

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [11]:
import numpy as np

def sum_rows_2d(array):
    """
    Function to compute the sum of each row in a 2D array.
    
    Parameters:
    array (2D array-like): The input two-dimensional array (list of lists or NumPy array).
    
    Returns:
    list: A list containing the sum of each row in the input 2D array.
    """
    # Ensure the input is a NumPy array for ease of operations
    array = np.array(array)
    
    # Compute the sum of each row using np.sum with axis=1 (axis=1 refers to rows)
    row_sums = np.sum(array, axis=1)
    
    return row_sums

# Example usage:
# Defining a 2D list (matrix)
my_2d_array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Call the function with the 2D array
result = sum_rows_2d(my_2d_array)

# Print the result
print("Sum of each row:", result)


Sum of each row: [ 6 15 24]


In 2-3 sentences, describe what section of the website helped you write your function. 

In [ ]:
# The section on NumPy Arrays from the W3Schools website helped me write the function by explaining how to work with 
# 2D arrays (or matrices) in NumPy. 
# Specifically, the examples showing how to use np.array() to convert lists into arrays and np.sum(axis=1) for summing 
# across rows illustrated how to add my arrays.

# For the question below

def second_value_each_row(nested_list):
    # Use list comprehension to extract the second element from each row
    return [row[1] for row in nested_list if len(row) > 1]

# Example usage
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8]]
result = second_value_each_row(nested_list)
print(result)  # Output: [2, 5, 8]

# The function second_value_each_row iterates through each row in the nested_list and extracts the second value 
# (row[1]).
# The condition if len(row) > 1 ensures that rows with at least two elements are included, preventing an IndexError 
# for rows with fewer than two elements.



How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [13]:
import numpy as np

def filter_rows_by_sum(array, threshold):
    """
    Function to filter rows of a 2D array based on the sum of the elements.
    Keeps only rows where the sum of the elements is greater than or equal to the threshold.
    
    Parameters:
    array (2D array-like): The input two-dimensional array (list of lists or NumPy array).
    threshold (int or float): The threshold for the sum of each row.
    
    Returns:
    np.ndarray: A new 2D NumPy array containing only the rows that meet the condition.
    """
    # Ensure the input is a NumPy array (in case it is passed as a list of lists)
    array = np.array(array)
    
    # Create an empty list to store rows that meet the condition
    filtered_rows = []

    # Iterate through each row in the 2D array
    for row in array:
        # Calculate the sum of elements in the current row
        row_sum = np.sum(row)
        
        # Check if the sum of the current row is greater than or equal to the threshold
        if row_sum >= threshold:
            # If the condition is met, add this row to the filtered list
            filtered_rows.append(row)
        else:
            # If the condition is not met, you can print it or perform other actions
            print(f"Row {row} has been filtered out (sum = {row_sum})")

    # Convert the filtered rows list back to a NumPy array and return it
    return np.array(filtered_rows)


# Example usage
# Define a 2D array
array_2d = [
    [1, 2, 3],    # Sum = 6
    [4, 5, 6],    # Sum = 15
    [1, 1, 1],    # Sum = 3
    [10, 20, 30]  # Sum = 60
]

# Set the threshold value
threshold_value = 10

# Call the function and print the filtered result
filtered_array = filter_rows_by_sum(array_2d, threshold_value)
print("\nFiltered Rows (Sum >= threshold):")
print(filtered_array)


Row [1 2 3] has been filtered out (sum = 6)
Row [1 1 1] has been filtered out (sum = 3)

Filtered Rows (Sum >= threshold):
[[ 4  5  6]
 [10 20 30]]


In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [14]:
def matrix_multiplication():
    # Test Case 1: Matrix multiplication with np.dot
    matrix1 = np.array([[1, 2], [3, 4]])
    matrix2 = np.array([[5, 6], [7, 8]])
    result_matrix = np.dot(matrix1, matrix2)
    print("Test Case 1 - Matrix Multiplication using np.dot:\n", result_matrix)
    
    # Test Case 2: Matrix multiplication using @ operator
    result_matrix_2 = matrix1 @ matrix2
    print("Test Case 2 - Matrix Multiplication using @ operator:\n", result_matrix_2)

matrix_multiplication()


Test Case 1 - Matrix Multiplication using np.dot:
 [[19 22]
 [43 50]]
Test Case 2 - Matrix Multiplication using @ operator:
 [[19 22]
 [43 50]]


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [37]:
#My matrix_multiplication function took inspiration from the Matrix Multiplication section of the NumPy 
# tutorial. It demonstrates how to perform matrix multiplication using both the np.dot() function and the @ operator, 
# which are essential for linear algebra in NumPy. The function covers how these methods handle 2D array 
# multiplication, ensuring that the result is computed correctly for both row-by-column and element-wise operations.





# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [22]:
# Directly import the function from the even_sum module
from even_sum import sum_even_numbers

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [23]:

# Define own list of numbers  (can modify this as needed)
numbers = [10, 15, 22, 30, 37, 50, 61, 74, 81, 99]

# Call the sum_even_numbers function with list of numbers
result = sum_even_numbers(numbers)

# Print the result
print(f"The sum of even numbers in the list is: {result}")


The sum of even numbers in the list is: 186


I have provided you a separate module called `example.py`. Import that module here.

In [44]:
from example import rocket_launch 
from example import orbital_velocity 
from example import escape_velocity

With the following variables, use my module to show which of the rocket's escape!

In [46]:
#Code really did not want to work and kept giving me the same error even when I altered the function and re imported it
#so I'm writing my own code for this, and using my own examples

import numpy as np

# Function to calculate escape velocity
def escape_velocity(mass, radius):
    """Calculates escape velocity for a planet."""
    G = 6.67430e-11  # Gravitational constant
    return np.sqrt(2 * G * mass / radius)

# Function to calculate orbital velocity
def orbital_velocity(mass, radius):
    """Calculates orbital velocity for a planet."""
    G = 6.67430e-11
    return np.sqrt(G * mass / radius)

def rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet):
    """
    Determines if a rocket can escape based on its final velocity.

    Inputs:
    rocket_velocities (numpy.ndarray): List of rocket velocities in meters per second
    mass_of_planet (float): Mass of the planet in kilograms
    radius_of_planet (float): Radius of the planet in meters

    Output:
    statuses (list): Statements for each rocket describing its status.
    """
    
    # Calculate escape and orbital velocities
    esc_velocity = escape_velocity(mass_of_planet, radius_of_planet)
    orb_velocity = orbital_velocity(mass_of_planet, radius_of_planet)
    
    statuses = []  # To store the status of each rocket

    # Loop through each rocket's velocity
    for rocket_velocity in rocket_velocities:
        # Use the velocity directly, no need for rocket[-1]
        final_velocity_of_rocket = rocket_velocity
        
        # Determine the rocket's status based on its velocity
        if final_velocity_of_rocket < orb_velocity:
            statement = "Rocket crashes back into the planet!"
        
        elif orb_velocity <= final_velocity_of_rocket < esc_velocity:
            statement = "Rocket is orbiting around the planet."
        
        else:
            statement = "Rocket left the planet!"
        
        # Append the status for the rocket
        statuses.append(statement)

    return statuses

# Test case
rocket_velocities = np.array([5000, 8000, 12000, 15000])  # List of rocket velocities in m/s
mass_of_planet = 5.97e24  # Earth's mass in kilograms
radius_of_planet = 6.37e6  # Earth's radius in meters

# Call the function
statuses = rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet)

# Print the results
for i, status in enumerate(statuses):
    print(f"Rocket {i+1}: {status}")



Rocket 1: Rocket crashes back into the planet!
Rocket 2: Rocket is orbiting around the planet.
Rocket 3: Rocket left the planet!
Rocket 4: Rocket left the planet!


In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [ ]:
#I offered an overview of every step and was able to work around an issue that presented itself in the imported function not working.
#That being said, the names of the functions could be more descriptive. For example, rocket launch is not describing the launch of a 
#rocket, rather it is describing the end behavior of that rocket as a function of its velocity and of the radius and mass of the planet, so
#instead of rocket launch it could be named will_the_rocket_escape_the_earth's_gravity?

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [ ]:
# I made a kinematics/projectile motion module that calculates trajectory, maximum height, and horizontal range.
# I hate doing kinematics so I wanted to create a module that would speed up all the algebra you have to do. With just the initial velocity 
# and launch angle you can calculate max height, horizontal range, and the trajectory of the object.

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [30]:
# Using all of the coding knowledge I have gathered over the past couple weeks. I do not have any formal coding expereince so learning 
# all of functions, having to implement for loops and elif statements, and utilizing imports was all kind of a slog at first. Generally
# I just got better at coding and it's nice to be better at something like this.

Once your module is complete, import it here.

In [52]:
from Projectile_Motion import calculate_trajectory
from Projectile_Motion import maximum_height
from Projectile_Motion import horizontal_range_and_time_of_flight

Call each of your functions in the cell below. Make sure to show the outputs! 

In [73]:
initial_velocity = x = 20
launch_angle = y = 45

print(maximum_height(x,y))
print(calculate_trajectory(x,y,num_points=3))
print(horizontal_range_and_time_of_flight(x,y))

10.193679918450558
[[ 0.          0.          0.        ]
 [ 1.44160404 20.38735984 10.19367992]
 [ 2.88320808 40.77471967  0.        ]]
(40.77471967380224, 2.8832080782326095)


# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!